# Generated by Django 4.2.9 on 2026-01-28 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('boat_type', models.CharField(choices=[('sailboat', 'Парусная яхта'), ('motorboat', 'Моторная лодка'), ('catamaran', 'Катамаран'), ('yacht', 'Яхта'), ('speedboat', 'Катер')], max_length=20, verbose_name='Тип')),
                ('description', models.TextField(verbose_name='Описание')),
                ('location', models.CharField(max_length=200, verbose_name='Местоположение')),
                ('capacity', models.IntegerField(verbose_name='Вместимость (чел.)')),
                ('length', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Длина (м)')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена/день (₽)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='boats/', verbose_name='Фото')),
                ('available', models.BooleanField(default=True, verbose_name='Доступна')),
                ('cabins', models.IntegerField(default=0, verbose_name='Кают')),
                ('bathrooms', models.IntegerField(default=0, verbose_name='Санузлов')),
                ('has_skipper', models.BooleanField(default=False, verbose_name='Шкипер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boats', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Лодка',
                'verbose_name_plural': 'Лодки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParsedBoat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boat_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='ID лодки')),
                ('slug', models.CharField(db_index=True, max_length=200, verbose_name='Slug')),
                ('source_url', models.URLField(blank=True, max_length=500, verbose_name='URL источника')),
                ('boat_data', models.JSONField(default=dict, verbose_name='Данные лодки')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Название')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Локация')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Производитель')),
                ('year', models.CharField(blank=True, max_length=10, verbose_name='Год')),
                ('last_parsed', models.DateTimeField(auto_now=True, verbose_name='Последний парсинг')),
                ('images_downloaded', models.BooleanField(default=False, verbose_name='Фото скачаны')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('parse_count', models.IntegerField(default=1, verbose_name='Раз парсили')),
                ('last_parse_success', models.BooleanField(default=True, verbose_name='Последний парсинг успешен')),
            ],
            options={
                'verbose_name': 'Кэшированная лодка',
                'verbose_name_plural': 'Кэшированные лодки',
                'ordering': ['-last_parsed'],
                'indexes': [models.Index(fields=['boat_id'], name='boats_parse_boat_id_bba844_idx'), models.Index(fields=['slug'], name='boats_parse_slug_59e282_idx'), models.Index(fields=['last_parsed'], name='boats_parse_last_pa_fe3de6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('guests', models.IntegerField(default=1, verbose_name='Гостей')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='pending', max_length=20, verbose_name='Статус')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итого (₽)')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='boats.boat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оценка')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='boats.boat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
                'unique_together': {('boat', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('offer_type', models.CharField(choices=[('tourist', 'Туристический'), ('captain', 'Капитанский')], default='tourist', help_text='Туристический - красивый UI. Капитанский - детальная информация.', max_length=20, verbose_name='Тип оффера')),
                ('source_url', models.URLField(max_length=500, verbose_name='URL источника')),
                ('check_in', models.DateField(verbose_name='Дата заезда')),
                ('check_out', models.DateField(verbose_name='Дата выезда')),
                ('boat_data', models.JSONField(default=dict, verbose_name='Данные лодки')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая цена')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оригинальная цена')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Скидка')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Валюта')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('notes', models.TextField(blank=True, help_text='Внутренние заметки, не видны клиенту', verbose_name='Заметки')),
                ('show_countdown', models.BooleanField(default=True, verbose_name='Показать таймер')),
                ('notifications', models.JSONField(blank=True, default=list, verbose_name='Уведомления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Действителен до')),
                ('views_count', models.IntegerField(default=0, verbose_name='Просмотров')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_offers', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Оффер',
                'verbose_name_plural': 'Офферы',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['uuid'], name='boats_offer_uuid_c51d3b_idx'), models.Index(fields=['offer_type'], name='boats_offer_offer_t_ebc893_idx'), models.Index(fields=['-created_at'], name='boats_offer_created_66ef65_idx')],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='boats.boat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'boat')},
            },
        ),
    ]
