# Generated by Django 4.2.9 on 2026-01-31 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parsedboat',
            options={'ordering': ['-last_parsed'], 'verbose_name': 'Лодка (базовая информация)', 'verbose_name_plural': 'Лодки (базовая информация)'},
        ),
        migrations.RemoveField(
            model_name='parsedboat',
            name='boat_data',
        ),
        migrations.RemoveField(
            model_name='parsedboat',
            name='images_downloaded',
        ),
        migrations.RemoveField(
            model_name='parsedboat',
            name='location',
        ),
        migrations.RemoveField(
            model_name='parsedboat',
            name='title',
        ),
        migrations.AddField(
            model_name='parsedboat',
            name='model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='parsedboat',
            name='slug',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='parsedboat',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год выпуска'),
        ),
        migrations.CreateModel(
            name='BoatTechnicalSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Длина (м)')),
                ('beam', models.FloatField(blank=True, null=True, verbose_name='Ширина (м)')),
                ('draft', models.FloatField(blank=True, null=True, verbose_name='Осадка (м)')),
                ('cabins', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Кабины')),
                ('berths', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Спальных мест (max)')),
                ('toilets', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Туалеты')),
                ('fuel_capacity', models.IntegerField(blank=True, null=True, verbose_name='Топливо (л)')),
                ('water_capacity', models.IntegerField(blank=True, null=True, verbose_name='Вода (л)')),
                ('waste_capacity', models.IntegerField(blank=True, null=True, verbose_name='Сточные воды (л)')),
                ('max_speed', models.FloatField(blank=True, null=True, verbose_name='Макс скорость (узлы)')),
                ('engine_power', models.IntegerField(blank=True, null=True, verbose_name='Мощность (л.с.)')),
                ('number_engines', models.IntegerField(blank=True, null=True, verbose_name='Количество двигателей')),
                ('engine_type', models.CharField(blank=True, max_length=50, verbose_name='Тип двигателя')),
                ('fuel_type', models.CharField(blank=True, max_length=50, verbose_name='Тип топлива')),
                ('renovated_year', models.IntegerField(blank=True, null=True, verbose_name='Год ремонта')),
                ('sail_renovated_year', models.IntegerField(blank=True, null=True, verbose_name='Год ремонта парусов')),
                ('boat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_specs', to='boats.parsedboat')),
            ],
            options={
                'verbose_name': 'Технические параметры',
                'verbose_name_plural': 'Технические параметры',
            },
        ),
        migrations.CreateModel(
            name='BoatPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('EUR', '€ EUR'), ('USD', '$ USD'), ('GBP', '£ GBP'), ('RUB', '₽ RUB'), ('TRY', '₺ TRY'), ('CZK', 'Kč CZK'), ('PLN', 'zł PLN'), ('SEK', 'kr SEK'), ('NOK', 'kr NOK'), ('DKK', 'kr DKK')], max_length=3, verbose_name='Валюта')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена/день')),
                ('price_per_week', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена/неделя')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='boats.parsedboat')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
                'indexes': [models.Index(fields=['boat', 'currency'], name='boats_boatp_boat_id_aeb796_idx')],
                'unique_together': {('boat', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='BoatGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdn_url', models.URLField(max_length=500, verbose_name='URL фото на CDN')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='boats.parsedboat')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['boat', 'order'], name='boats_boatg_boat_id_aed512_idx')],
            },
        ),
        migrations.CreateModel(
            name='BoatDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru_RU', 'Русский'), ('en_EN', 'English'), ('en_US', 'English (US)'), ('en_GB', 'English (UK)'), ('es_ES', 'Español'), ('de_DE', 'Deutsch'), ('fr_FR', 'Français'), ('it_IT', 'Italiano'), ('pt_PT', 'Português'), ('nl_NL', 'Nederlands'), ('pl_PL', 'Polski'), ('tr_TR', 'Türkçe')], max_length=10, verbose_name='Язык')),
                ('extras', models.JSONField(default=list, verbose_name='Опции (extras)')),
                ('additional_services', models.JSONField(default=list, verbose_name='Доп. услуги')),
                ('delivery_extras', models.JSONField(default=list, verbose_name='Опции доставки')),
                ('not_included', models.JSONField(default=list, verbose_name='Не включено в цену')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='boats.parsedboat')),
            ],
            options={
                'verbose_name': 'Доп. детали',
                'verbose_name_plural': 'Доп. детали',
                'indexes': [models.Index(fields=['boat', 'language'], name='boats_boatd_boat_id_f0dd11_idx')],
                'unique_together': {('boat', 'language')},
            },
        ),
        migrations.CreateModel(
            name='BoatDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru_RU', 'Русский'), ('en_EN', 'English'), ('en_US', 'English (US)'), ('en_GB', 'English (UK)'), ('es_ES', 'Español'), ('de_DE', 'Deutsch'), ('fr_FR', 'Français'), ('it_IT', 'Italiano'), ('pt_PT', 'Português'), ('nl_NL', 'Nederlands'), ('pl_PL', 'Polski'), ('tr_TR', 'Türkçe')], max_length=10, verbose_name='Язык')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Локация')),
                ('marina', models.CharField(blank=True, max_length=200, verbose_name='Марина')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='boats.parsedboat')),
            ],
            options={
                'verbose_name': 'Описание',
                'verbose_name_plural': 'Описания',
                'indexes': [models.Index(fields=['boat', 'language'], name='boats_boatd_boat_id_22f91b_idx')],
                'unique_together': {('boat', 'language')},
            },
        ),
    ]
