# Generated by Django 4.2.9 on 2026-01-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0002_alter_parsedboat_options_remove_parsedboat_boat_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boatdescription',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='boatdescription',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='boatdescription',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Регион/Область'),
        ),
    ]
