# Generated by Django 4.2.9 on 2026-01-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0003_boatdescription_city_boatdescription_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boatdetails',
            name='cockpit',
            field=models.JSONField(default=list, verbose_name='Оборудование кокпита'),
        ),
        migrations.AddField(
            model_name='boatdetails',
            name='entertainment',
            field=models.JSONField(default=list, verbose_name='Развлечения'),
        ),
        migrations.AddField(
            model_name='boatdetails',
            name='equipment',
            field=models.JSONField(default=list, verbose_name='Оборудование'),
        ),
    ]
