# Generated by Django 4.2.9 on 2026-02-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0004_boatdetails_cockpit_boatdetails_entertainment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='source_url',
            field=models.TextField(max_length=500, verbose_name='URL источника'),
        ),
    ]
