# Generated by Django 4.2.9 on 2026-02-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0005_change_source_url_to_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='has_meal',
            field=models.BooleanField(default=False, help_text='Только для туристических офферов', verbose_name='Включено питание'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='source_url',
            field=models.URLField(max_length=500, verbose_name='URL источника'),
        ),
    ]
