# Generated by Django 4.2.9 on 2026-02-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0006_offer_has_meal_alter_offer_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='source_url',
            field=models.TextField(help_text='URL лодки с boataround.com (включает параметры checkIn и checkOut)', max_length=2000, verbose_name='URL источника'),
        ),
    ]
