# Generated by Django 4.2.9 on 2026-02-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0007_alter_offer_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedboat',
            name='boat_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Кэшированные данные'),
        ),
    ]
