# Generated by Django 4.2.9 on 2026-02-02 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0009_update_favorite_to_parsed_boat'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='favorite',
            new_name='boats_favor_user_id_4d771f_idx',
            old_name='boats_favor_user_id_boat_sl_idx',
        ),
        migrations.RenameIndex(
            model_name='favorite',
            new_name='boats_favor_user_id_906902_idx',
            old_name='boats_favor_user_id_created_idx',
        ),
    ]
