# Generated by Django 4.2.9 on 2026-02-02 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0010_rename_boats_favor_user_id_boat_sl_idx_boats_favor_user_id_4d771f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='boat_data',
            field=models.JSONField(default=dict, verbose_name='Данные лодки'),
        ),
        migrations.AddField(
            model_name='booking',
            name='currency',
            field=models.CharField(default='EUR', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='booking',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='boats.offer'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='boat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='boats.boat'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итого'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', '-created_at'], name='boats_booki_user_id_287d66_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', '-created_at'], name='boats_booki_status_b2128e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['offer'], name='boats_booki_offer_i_d54a9e_idx'),
        ),
    ]
