# Generated by Django 4.2.9 on 2026-02-02 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0011_booking_boat_data_booking_currency_booking_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='parsed_boat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='boats.parsedboat'),
        ),
    ]
