# Generated by Django 4.2.9 on 2026-02-12 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0012_booking_parsed_boat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charter_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='ID чартера')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('logo', models.CharField(blank=True, max_length=500, verbose_name='Логотип (путь)')),
                ('commission', models.DecimalField(decimal_places=2, default=0, help_text='Процент комиссии, добавляемый к итоговой цене', max_digits=5, verbose_name='Комиссия (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Чартерная компания',
                'verbose_name_plural': 'Чартерные компании',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['charter_id'], name='boats_chart_charter_3f84f3_idx')],
            },
        ),
        migrations.AddField(
            model_name='parsedboat',
            name='charter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boats', to='boats.charter', verbose_name='Чартерная компания'),
        ),
    ]
