# Generated by Django 4.2.9 on 2026-02-13 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boats', '0017_offer_branding_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='assigned_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер'),
        ),
    ]
