# Generated by Django 4.2.9 on 2026-02-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0018_booking_assigned_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedboat',
            name='preview_cdn_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Превью на CDN'),
        ),
    ]
