# Generated by Django 4.2.9 on 2026-02-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0019_add_preview_cdn_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='price_adjustment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Положительное значение — наценка, отрицательное — скидка', max_digits=10, verbose_name='Корректировка цены'),
        ),
    ]
