# Generated by Django 4.2.9 on 2026-03-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0021_pricesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricesettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
