# Generated by Django 4.2.9 on 2026-03-22 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boats', '0022_alter_pricesettings_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('contract_type', models.CharField(choices=[('agent_rental', 'Агентский договор аренды'), ('captain_services', 'Договор капитанских услуг')], max_length=30, unique=True, verbose_name='Тип договора')),
                ('template_content', models.TextField(help_text='Django template markup для генерации PDF', verbose_name='Содержимое шаблона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Шаблон договора',
                'verbose_name_plural': 'Шаблоны договоров',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='Номер договора')),
                ('contract_data', models.JSONField(default=dict, help_text='ФИО, паспорт, условия и т.д.', verbose_name='Данные договора')),
                ('document_file', models.FileField(blank=True, upload_to='contracts/documents/', verbose_name='PDF документ')),
                ('signed_file', models.FileField(blank=True, upload_to='contracts/signed/', verbose_name='Подписанный PDF')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('viewed', 'Просмотрен'), ('signed', 'Подписан'), ('rejected', 'Отклонён'), ('expired', 'Истёк')], default='draft', max_length=20, verbose_name='Статус')),
                ('signature_data', models.TextField(blank=True, verbose_name='Данные подписи (base64)')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подписания')),
                ('sign_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP подписания')),
                ('sign_user_agent', models.TextField(blank=True, verbose_name='User-Agent подписания')),
                ('document_hash', models.CharField(blank=True, max_length=64, verbose_name='SHA-256 хэш документа')),
                ('sign_token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Токен подписания')),
                ('expires_at', models.DateTimeField(verbose_name='Действителен до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='boats.booking', verbose_name='Бронирование')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Создатель (агент)')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='boats.offer', verbose_name='Оффер')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_to_sign', to=settings.AUTH_USER_MODEL, verbose_name='Подписант (клиент)')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='boats.contracttemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['uuid'], name='boats_contr_uuid_6ecdf3_idx'), models.Index(fields=['sign_token'], name='boats_contr_sign_to_7a8ae2_idx'), models.Index(fields=['status'], name='boats_contr_status_8329c6_idx'), models.Index(fields=['-created_at'], name='boats_contr_created_efb073_idx')],
            },
        ),
    ]
