# Generated by Django 4.2.9 on 2026-03-24 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boats', '0023_contracttemplate_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('passport_number', models.CharField(blank=True, max_length=50, verbose_name='Номер паспорта')),
                ('passport_issued_by', models.CharField(blank=True, max_length=200, verbose_name='Кем выдан')),
                ('passport_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_clients', to=settings.AUTH_USER_MODEL, verbose_name='Создал (агент/капитан)'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт пользователя'),
        ),
        migrations.AddField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='boats.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='boats.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='offer',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='boats.client', verbose_name='Клиент'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client'], name='boats_booki_client__2b4cf4_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['created_by', '-created_at'], name='boats_clien_created_e6f884_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['last_name', 'first_name'], name='boats_clien_last_na_adf6cc_idx'),
        ),
    ]
