# Generated by Django 4.2.9 on 2026-03-24 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0024_client_booking_boats_booki_client__2b4cf4_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Код')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('delivery_method', models.CharField(choices=[('sms', 'SMS'), ('telegram', 'Telegram')], default='sms', max_length=20, verbose_name='Способ доставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Попытки ввода')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Подтверждён')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to='boats.contract')),
            ],
            options={
                'verbose_name': 'OTP код договора',
                'verbose_name_plural': 'OTP коды договоров',
                'ordering': ['-created_at'],
            },
        ),
    ]
