# Generated by Django 4.2.9 on 2026-03-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0025_add_contractotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractotp',
            name='delivery_method',
            field=models.CharField(choices=[('sms', 'SMS')], default='sms', max_length=20, verbose_name='Способ доставки'),
        ),
    ]
