# Generated by Django 5.2.12 on 2026-03-26 20:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0026_alter_contractotp_delivery_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boatdescription',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='boatdetails',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='boatprice',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='boatdescription',
            constraint=models.UniqueConstraint(fields=('boat', 'language'), name='unique_boat_description_language'),
        ),
        migrations.AddConstraint(
            model_name='boatdetails',
            constraint=models.UniqueConstraint(fields=('boat', 'language'), name='unique_boat_details_language'),
        ),
        migrations.AddConstraint(
            model_name='boatprice',
            constraint=models.UniqueConstraint(fields=('boat', 'currency'), name='unique_boat_price_currency'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'boat_slug'), name='unique_user_boat_slug'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('boat', 'user'), name='unique_boat_user_review'),
        ),
    ]
