# Generated by Django 5.2.12 on 2026-03-30 14:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0027_alter_boatdescription_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='price_captain',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Капитан'),
        ),
        migrations.AddField(
            model_name='offer',
            name='price_fuel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Топливо'),
        ),
        migrations.AddField(
            model_name='offer',
            name='price_moorings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоянки'),
        ),
        migrations.AddField(
            model_name='offer',
            name='price_transit_cleaning',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Транзит лог и клининг'),
        ),
        migrations.AddField(
            model_name='offer',
            name='price_trips_markup',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Наценка Трипс'),
        ),
        migrations.AddField(
            model_name='pricesettings',
            name='tourist_captain_default',
            field=models.DecimalField(decimal_places=2, default=Decimal('900.00'), max_digits=8, verbose_name='Капитан по умолчанию (EUR)'),
        ),
        migrations.AddField(
            model_name='pricesettings',
            name='tourist_captain_seychelles',
            field=models.DecimalField(decimal_places=2, default=Decimal('900.00'), max_digits=8, verbose_name='Капитан Сейшелы (EUR)'),
        ),
        migrations.AddField(
            model_name='pricesettings',
            name='tourist_captain_turkey',
            field=models.DecimalField(decimal_places=2, default=Decimal('880.00'), max_digits=8, verbose_name='Капитан Турция (EUR)'),
        ),
        migrations.AddField(
            model_name='pricesettings',
            name='tourist_fuel_default',
            field=models.DecimalField(decimal_places=2, default=Decimal('900.00'), max_digits=8, verbose_name='Топливо по умолчанию (EUR)'),
        ),
        migrations.AddField(
            model_name='pricesettings',
            name='tourist_fuel_seychelles',
            field=models.DecimalField(decimal_places=2, default=Decimal('900.00'), max_digits=8, verbose_name='Топливо Сейшелы (EUR)'),
        ),
        migrations.AddField(
            model_name='pricesettings',
            name='tourist_fuel_turkey',
            field=models.DecimalField(decimal_places=2, default=Decimal('880.00'), max_digits=8, verbose_name='Топливо Турция (EUR)'),
        ),
        migrations.AddField(
            model_name='pricesettings',
            name='tourist_moorings_default',
            field=models.DecimalField(decimal_places=2, default=Decimal('900.00'), max_digits=8, verbose_name='Стоянки по умолчанию (EUR)'),
        ),
        migrations.AddField(
            model_name='pricesettings',
            name='tourist_moorings_seychelles',
            field=models.DecimalField(decimal_places=2, default=Decimal('900.00'), max_digits=8, verbose_name='Стоянки Сейшелы (EUR)'),
        ),
        migrations.AddField(
            model_name='pricesettings',
            name='tourist_moorings_turkey',
            field=models.DecimalField(decimal_places=2, default=Decimal('880.00'), max_digits=8, verbose_name='Стоянки Турция (EUR)'),
        ),
        migrations.AddField(
            model_name='pricesettings',
            name='tourist_transit_cleaning_default',
            field=models.DecimalField(decimal_places=2, default=Decimal('900.00'), max_digits=8, verbose_name='Транзит лог и клининг по умолчанию (EUR)'),
        ),
        migrations.AddField(
            model_name='pricesettings',
            name='tourist_transit_cleaning_seychelles',
            field=models.DecimalField(decimal_places=2, default=Decimal('900.00'), max_digits=8, verbose_name='Транзит лог и клининг Сейшелы (EUR)'),
        ),
        migrations.AddField(
            model_name='pricesettings',
            name='tourist_transit_cleaning_turkey',
            field=models.DecimalField(decimal_places=2, default=Decimal('880.00'), max_digits=8, verbose_name='Транзит лог и клининг Турция (EUR)'),
        ),
        migrations.AddField(
            model_name='pricesettings',
            name='tourist_trips_markup_default',
            field=models.DecimalField(decimal_places=2, default=Decimal('900.00'), max_digits=8, verbose_name='Наценка Трипс по умолчанию (EUR)'),
        ),
        migrations.AddField(
            model_name='pricesettings',
            name='tourist_trips_markup_seychelles',
            field=models.DecimalField(decimal_places=2, default=Decimal('900.00'), max_digits=8, verbose_name='Наценка Трипс Сейшелы (EUR)'),
        ),
        migrations.AddField(
            model_name='pricesettings',
            name='tourist_trips_markup_turkey',
            field=models.DecimalField(decimal_places=2, default=Decimal('880.00'), max_digits=8, verbose_name='Наценка Трипс Турция (EUR)'),
        ),
        migrations.AlterField(
            model_name='pricesettings',
            name='tourist_default_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('4500.00'), max_digits=8, verbose_name='Базовая цена по умолчанию (EUR) (deprecated)'),
        ),
        migrations.AlterField(
            model_name='pricesettings',
            name='tourist_seychelles_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('4500.00'), max_digits=8, verbose_name='Базовая цена Сейшелы (EUR) (deprecated)'),
        ),
        migrations.AlterField(
            model_name='pricesettings',
            name='tourist_turkey_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('4400.00'), max_digits=8, verbose_name='Базовая цена Турция (EUR) (deprecated)'),
        ),
    ]
