# Generated by Django 5.2.12 on 2026-03-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0030_countrypriceconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='boattechnicalspecs',
            name='allowed_people',
            field=models.IntegerField(blank=True, null=True, verbose_name='Разрешено гостей'),
        ),
        migrations.AddField(
            model_name='boattechnicalspecs',
            name='cabins_with_bunk_bed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Каюты с двухъярус. кроватью'),
        ),
        migrations.AddField(
            model_name='boattechnicalspecs',
            name='crew_sleeps',
            field=models.IntegerField(blank=True, null=True, verbose_name='Спальных мест экипажа'),
        ),
        migrations.AddField(
            model_name='boattechnicalspecs',
            name='cruising_consumption',
            field=models.FloatField(blank=True, null=True, verbose_name='Расход на крейс. скорости'),
        ),
        migrations.AddField(
            model_name='boattechnicalspecs',
            name='double_cabins',
            field=models.IntegerField(blank=True, null=True, verbose_name='Двухместные каюты'),
        ),
        migrations.AddField(
            model_name='boattechnicalspecs',
            name='quadruple_cabins',
            field=models.IntegerField(blank=True, null=True, verbose_name='Четырёхместные каюты'),
        ),
        migrations.AddField(
            model_name='boattechnicalspecs',
            name='saloon_sleeps',
            field=models.IntegerField(blank=True, null=True, verbose_name='Спальных мест в салоне'),
        ),
        migrations.AddField(
            model_name='boattechnicalspecs',
            name='single_cabins',
            field=models.IntegerField(blank=True, null=True, verbose_name='Одноместные каюты'),
        ),
        migrations.AddField(
            model_name='boattechnicalspecs',
            name='total_engine_power',
            field=models.IntegerField(blank=True, null=True, verbose_name='Суммарная мощность (л.с.)'),
        ),
        migrations.AddField(
            model_name='boattechnicalspecs',
            name='triple_cabins',
            field=models.IntegerField(blank=True, null=True, verbose_name='Трёхместные каюты'),
        ),
        migrations.AddField(
            model_name='charter',
            name='rank_out_of',
            field=models.IntegerField(blank=True, null=True, verbose_name='Всего в рейтинге'),
        ),
        migrations.AddField(
            model_name='charter',
            name='rank_place',
            field=models.IntegerField(blank=True, null=True, verbose_name='Место в рейтинге'),
        ),
        migrations.AddField(
            model_name='charter',
            name='rank_reviews_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во отзывов'),
        ),
        migrations.AddField(
            model_name='charter',
            name='rank_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='parsedboat',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='parsedboat',
            name='category_slug',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Slug категории'),
        ),
        migrations.AddField(
            model_name='parsedboat',
            name='flag',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Флаг страны'),
        ),
        migrations.AddField(
            model_name='parsedboat',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='parsedboat',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='parsedboat',
            name='newboat',
            field=models.BooleanField(default=False, verbose_name='Новая лодка'),
        ),
        migrations.AddField(
            model_name='parsedboat',
            name='prepayment',
            field=models.IntegerField(blank=True, null=True, verbose_name='Предоплата (%)'),
        ),
        migrations.AddField(
            model_name='parsedboat',
            name='reviews_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='parsedboat',
            name='sail',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Парус'),
        ),
        migrations.AddField(
            model_name='parsedboat',
            name='total_reviews',
            field=models.IntegerField(blank=True, null=True, verbose_name='Всего отзывов'),
        ),
        migrations.AddField(
            model_name='parsedboat',
            name='usp',
            field=models.JSONField(blank=True, default=list, verbose_name='USP (уникальные преимущества)'),
        ),
        migrations.AddIndex(
            model_name='parsedboat',
            index=models.Index(fields=['category_slug'], name='boats_parse_categor_d598ae_idx'),
        ),
    ]
