# Generated by Django 5.2.12 on 2026-04-01 11:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0031_api_metadata_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParseJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID задания')),
                ('mode', models.CharField(choices=[('api', 'Только API-метаданные'), ('html', 'Только HTML-парсинг'), ('full', 'Полный (API + HTML)')], default='full', max_length=10, verbose_name='Режим')),
                ('destination', models.CharField(blank=True, default='', max_length=100, verbose_name='Направление')),
                ('max_pages', models.IntegerField(blank=True, null=True, verbose_name='Макс. страниц')),
                ('batch_size', models.IntegerField(default=50, verbose_name='Размер батча')),
                ('skip_existing', models.BooleanField(default=False, verbose_name='Пропускать существующие')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('collecting', "Сбор slug'ов"), ('running', 'Выполняется'), ('completed', 'Завершено'), ('failed', 'Ошибка'), ('partial', 'Частично'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Celery Task ID')),
                ('total_slugs', models.IntegerField(default=0, verbose_name="Всего slug'ов")),
                ('total_batches', models.IntegerField(default=0, verbose_name='Всего батчей')),
                ('batches_done', models.IntegerField(default=0, verbose_name='Батчей выполнено')),
                ('processed', models.IntegerField(default=0, verbose_name='Обработано')),
                ('success', models.IntegerField(default=0, verbose_name='Успешно')),
                ('failed', models.IntegerField(default=0, verbose_name='Ошибки')),
                ('skipped', models.IntegerField(default=0, verbose_name='Пропущено')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='Список ошибок')),
                ('summary', models.TextField(blank=True, default='', verbose_name='Краткий отчёт')),
                ('detailed_log', models.TextField(blank=True, default='', verbose_name='Подробный лог')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parse_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Кто запустил')),
            ],
            options={
                'verbose_name': 'Задание парсинга',
                'verbose_name_plural': 'Задания парсинга',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job_id'], name='boats_parse_job_id_045201_idx'), models.Index(fields=['status', '-created_at'], name='boats_parse_status_552d94_idx')],
            },
        ),
    ]
