# Generated by Django 5.2.12 on 2026-04-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0032_parse_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricesettings',
            name='agent_commission_pct',
            field=models.IntegerField(default=50, help_text='Доля агента от комиссии чартера. 50 = агент получает половину комиссии.', verbose_name='Комиссия агента (% от комиссии чартера)'),
        ),
    ]
