# Generated by Django 5.2.12 on 2026-04-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0034_booking_option_until_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsejob',
            name='mode',
            field=models.CharField(choices=[('api', 'API source-of-truth'), ('html', 'HTML: фото + сервисы'), ('full', 'HTML: полный профиль')], default='full', max_length=10, verbose_name='Режим'),
        ),
    ]
