# Generated by Django 5.2.12 on 2026-04-22 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0037_feedback'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='feedback',
            new_name='boats_feedb_created_100f32_idx',
            old_name='boats_feedb_created_idx',
        ),
        migrations.RenameIndex(
            model_name='feedback',
            new_name='boats_feedb_is_proc_f6d1a5_idx',
            old_name='boats_feedb_is_proc_idx',
        ),
    ]
