# Generated by Django 5.2.12 on 2026-04-29 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boats', '0040_notification_thread'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='boats_messa_thread__45a3eb_idx',
            old_name='boats_messa_thread__idx',
        ),
        migrations.RenameIndex(
            model_name='messageread',
            new_name='boats_messa_user_id_f64590_idx',
            old_name='boats_messa_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='thread',
            new_name='boats_threa_last_me_94fb49_idx',
            old_name='boats_threa_last_me_idx',
        ),
        migrations.RenameIndex(
            model_name='thread',
            new_name='boats_threa_booking_04f7c9_idx',
            old_name='boats_threa_booking_idx',
        ),
    ]
