# Generated by Django 4.2.9 on 2026-01-28 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('tourist', 'Турист'), ('captain', 'Капитан'), ('manager', 'Менеджер'), ('admin', 'Администратор')], default='tourist', help_text='\n<b>Роли пользователей:</b><br>\n• <b>Турист</b> - базовая роль. Поиск лодок, просмотр, добавление в избранное.<br>\n• <b>Капитан</b> - может создавать капитанские офферы (детальные, со всей информацией).<br>\n• <b>Менеджер</b> - может создавать туристические и капитанские офферы, управлять лодками.<br>\n• <b>Администратор</b> - полный доступ ко всем функциям системы.\n', max_length=20, verbose_name='Роль')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
