# Generated by Django 4.2.9 on 2026-02-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('tourist', 'Турист'), ('captain', 'Капитан'), ('manager', 'Менеджер'), ('admin', 'Администратор'), ('superadmin', 'Суперадмин')], default='tourist', help_text='\n<b>Роли пользователей:</b><br>\n• <b>Турист</b> - базовая роль. Поиск лодок, просмотр, добавление в избранное.<br>\n• <b>Капитан</b> - может создавать капитанские офферы (детальные, со всей информацией).<br>\n• <b>Менеджер</b> - может создавать туристические и капитанские офферы, управлять лодками.<br>\n• <b>Администратор</b> - полный доступ ко всем функциям системы.\n', max_length=20, verbose_name='Роль'),
        ),
    ]
